services:
  wp_mariadb:
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wp_network

  wp_php:
    build:
      context: ./php
    volumes:
      - ..:/var/www/html
    networks:
      - wp_network
    depends_on:
      - wp_mariadb

  wp_nginx:
    build:
      context: ./nginx
    ports:
      - "8090:80"
    volumes:
      - ..:/var/www/html
    networks:
      - wp_network
    depends_on:
      - wp_php

networks:
  wp_network:

volumes:
  mariadb_data: